server:
  port: 8080
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-binding-errors: always
    include-exception: true
    include-stacktrace: never

spring:
  application:
    name: uberto
  jackson:
    default-property-inclusion: non_null
  profiles:
    active: dev

  security:
    user:
      name: user
      password: password

  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/uberto
    username: admin
    password: patoniato
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    or.springframework.web: DEBUG
